## Vorbereitung: Benötigte Bibliotheken installieren

Bevor Sie mit den Aufgaben beginnen, stellen Sie sicher, dass alle notwendigen Python-Bibliotheken installiert sind.
Führen Sie dazu den folgenden Befehl in Ihrem Terminal oder in einer Notebook-Zelle aus:

```bash
pip install jupyterlab keras matplotlib numpy pandas scikit-learn scipy
```

Danach können Sie die Bibliotheken in Ihrem Code importieren und verwenden.

## Was ist scikit-learn?

scikit-learn ist eine weit verbreitete Python-Bibliothek für Machine Learning.
Sie stellt viele fertige Algorithmen zur Verfügung, z. B.:

* Klassifikation (z. B. Decision Trees)
* Regression
* Clustering
* Modellbewertung

In diesem Notebook wird **scikit-learn** verwendet, um Machine-Learning-Modelle für Entscheidungsbäume zu erstellen, zu trainieren und auszuwerten.

## Datensatz herunterladen

Am Anfang laden Sie den Datensatz von hier herunter: https://www.kaggle.com/datasets/uciml/iris/data 

Schauen Sie sich den Datensatz anschließend genau an und versuchen Sie zu verstehen, worum es in diesem Datensatz geht.

## Schritt 1: Bibliotheken importieren

**Erklärung:**  
Hier importieren wir alle Bibliotheken, die wir brauchen. `pandas` verwenden wir zum Laden und Bearbeiten der CSV-Datei. `matplotlib` brauchen wir für die Visualisierung des Entscheidungsbaums. Von `sklearn` importieren wir das Decision-Tree-Modell, die Funktion zum Aufteilen der Daten und Bewertungsmethoden.

In [21]:
# Bibliotheken importieren

import pandas as pd  
# pandas: Wird verwendet, um Daten zu laden und zu bearbeiten (z. B. CSV-Dateien)

import matplotlib.pyplot as plt  
# matplotlib: Bibliothek zum Erstellen von Diagrammen und Visualisierungen


from sklearn.tree import DecisionTreeClassifier, plot_tree  
# DecisionTreeClassifier: Modell für Entscheidungsbäume (Klassifikation)
# plot_tree: Funktion, um den Entscheidungsbaum grafisch darzustellen

from sklearn.model_selection import train_test_split  
# train_test_split: Teilt Daten in Trainings- und Testdaten auf

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix  
# accuracy_score: Berechnet die Genauigkeit des Modells
# classification_report: Liefert Precision, Recall, F1-Score (detaillierte Bewertung)
# confusion_matrix: Zeigt, wie viele Vorhersagen korrekt/falsch pro Klasse sind

In [8]:
# Now this will work
df = pd.read_csv('Iris.csv')
print(df.head())

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

## Schritt 2: CSV-Datei laden

**Erklärung:**  
In diesem Schritt laden wir die Datei `Iris.csv` in ein DataFrame. Ein DataFrame ist eine tabellarische Datenstruktur von pandas. Die Datei muss im gleichen Ordner wie das Notebook liegen, damit sie direkt mit `pd.read_csv()` geladen werden kann.

**Aufgabe:**  
Laden Sie die CSV-Datei `Iris.csv` in die Variable `df`.

**Lösung:**

In [9]:
df = pd.read_csv('Iris.csv')

## Schritt 3: Erste Zeilen anzeigen

**Erklärung:**  
Mit `df.head()` schauen wir uns die ersten fünf Zeilen der Tabelle an. Dadurch können wir prüfen, ob die Datei richtig geladen wurde und wie die Daten ungefähr aussehen.

**Aufgabe:**  
Zeigen Sie die ersten Zeilen des DataFrames an.

**Lösung:**

In [10]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

## Schritt 4: Spalten prüfen

**Erklärung:**  
Hier lassen wir uns alle Spaltennamen anzeigen. Das ist wichtig, damit wir wissen, welche Spalten als Eingabedaten verwendet werden können und welche Spalte die Zielvariable ist.

**Aufgabe:**  
Geben Sie alle Spaltennamen des DataFrames aus.

**Lösung:**

In [33]:
...# Alle Spaltennamen anzeigen
print(df.columns)

Index(['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

## Schritt 5: Id-Spalte entfernen

**Erklärung:**  
Falls eine Spalte `Id` vorhanden ist, entfernen wir sie. Diese Spalte ist nur eine Nummerierung und enthält keine sinnvolle Information für die Klassifikation der Iris-Blumen.

**Aufgabe:**  
Entfernen Sie die Spalte `Id`, falls sie im DataFrame vorhanden ist.

**Lösung:**

In [12]:
...# Entferne 'Id' Spalte falls vorhanden (ohne if-Abfragen)
df = df.drop(columns='Id', errors='ignore')
print("'Id' Spalte entfernt (falls vorhanden)")

'Id' Spalte entfernt (falls vorhanden)

In [34]:
# Zeige aktuelle Spalten an
print("Aktuelle Spalten:")
print(df.columns.tolist())
print(df.columns)

Aktuelle Spalten:
['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm', 'Species']
Index(['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

## Schritt 6: Features und Zielvariable trennen

**Erklärung:**  
Jetzt trennen wir die Eingabedaten von der Zielvariable. `X` enthält die Merkmale der Blume, also zum Beispiel Länge und Breite von Kelch- und Blütenblättern. `y` enthält die Klasse, also die Iris-Art.

**Aufgabe:**  
Erstellen Sie `X` mit allen Merkmalen und `y` mit der Zielspalte `Species`.

**Lösung:**

In [35]:
# Alternative 1: Using .drop()
X = df.drop(columns='Species')
y = df['Species']

# Alternative 2: Using .iloc (by position)
#X = df.iloc[:, :-1]  # All columns except the last one
#y = df.iloc[:, -1]   # Only the last column

In [36]:
#EXTRA CODE FROM Ben

# Show shape of the data
print(f"X Shape (Features): {X.shape}")
print(f"y Shape (Target): {y.shape}")

# Show the first 3 rows of X
print("\nFirst 3 rows of X (Features):")
print(X.head(3))

# Show the first 3 values of y
print("\nFirst 3 values of y (Target):")
print(y.head(3))

# Show column names of X
print("\nColumns in X:")
print(X.columns.tolist())

X Shape (Features): (150, 4)
y Shape (Target): (150,)

First 3 rows of X (Features):
   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2

First 3 values of y (Target):
0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
Name: Species, dtype: object

Columns in X:
['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']

## Schritt 7: Daten in Trainings- und Testdaten aufteilen

**Erklärung:**  
Die Daten werden in Trainingsdaten und Testdaten aufgeteilt. Mit den Trainingsdaten lernt das Modell. Mit den Testdaten prüfen wir später, wie gut das Modell neue, unbekannte Daten klassifizieren kann. Hier verwenden wir 80 Prozent Training und 20 Prozent Test.

In [17]:
from sklearn.model_selection import train_test_split

# Split data into training and test sets
# X = input data (features)
# y = target values (classes)

# We split the data into two parts:
# - Training data → for the model to learn from
# - Test data → to check how good the model is

X_train, X_test, y_train, y_test = train_test_split(
    
    X,  # Input data (e.g., SepalLength, PetalWidth, ...)
    
    y,  # Target variable (e.g., Iris species)
    
    test_size=0.2,  # 20% of data will be used for testing
                    # 80% remains for training
    
    random_state=42 # Ensures the split is always the same (reproducible)
)

In [18]:
print("Data Split Summary:")
print(f"Training data - X_train: {X_train.shape}")
print(f"Training data - y_train: {y_train.shape}")
print(f"Test data - X_test: {X_test.shape}")
print(f"Test data - y_test: {y_test.shape}")
print()
print(f"Training samples: {len(X_train)} ({len(X_train)/len(X)*100:.0f}%)")
print(f"Test samples: {len(X_test)} ({len(X_test)/len(X)*100:.0f}%)")

Data Split Summary:
Training data - X_train: (120, 4)
Training data - y_train: (120,)
Test data - X_test: (30, 4)
Test data - y_test: (30,)

Training samples: 120 (80%)
Test samples: 30 (20%)

In [ ]:
# Daten in Trainings- und Testdaten aufteilen

# X = Eingabedaten (Features)
# y = Zielwerte (Klassen)

# Wir teilen die Daten in zwei Teile:
# - Trainingsdaten → zum Lernen des Modells
# - Testdaten → zum Überprüfen, wie gut das Modell ist

X_train, X_test, y_train, y_test = train_test_split(
    
    X,  # Eingabedaten (z. B. SepalLength, PetalWidth, ...)
    
    y,  # Zielvariable (z. B. Iris-Art)
    
    test_size=0.2,  # 20% der Daten werden für den Test verwendet
                    # 80% bleiben fürs Training
    
    random_state=42 # sorgt dafür, dass die Aufteilung immer gleich ist
)

## Schritt 8: Decision Tree Modell erstellen

**Erklärung:**  
Hier erstellen wir das Modell. Ein Decision Tree trifft Entscheidungen anhand von Regeln. Mit `max_depth=3` begrenzen wir die Tiefe des Baums. Dadurch wird das Modell einfacher und Overfitting kann reduziert werden.

**Aufgabe:**  
### Aufgabe

Erstelle einen Decision Tree Classifier mit folgenden Parametern:

- `max_depth=3` (maximale Tiefe des Baums)
- `random_state=42` (für reproduzierbare Ergebnisse)
- `min_samples_leaf=10` (mindestens 10 Datenpunkte pro Blatt)

Speicheren Sie das Modell in einer Variable namens `model`.


**Lösung:**

In [22]:
from sklearn.tree import DecisionTreeClassifier

# Create Decision Tree model with specified parameters
model = DecisionTreeClassifier(
    max_depth=3,           # Maximum depth of the tree (limits complexity)
    random_state=42,       # Ensures reproducible results
    min_samples_leaf=10    # Minimum number of samples per leaf node
)

In [23]:
# Display the model parameters
print("Decision Tree Model created with parameters:")
print(f"   max_depth: {model.max_depth}")
print(f"   random_state: {model.random_state}")
print(f"   min_samples_leaf: {model.min_samples_leaf}")
print(f"\n Model ready for training!")

Decision Tree Model created with parameters:
   max_depth: 3
   random_state: 42
   min_samples_leaf: 10

 Model ready for training!

## Schritt 9: Modell trainieren

**Erklärung:**  
Jetzt trainieren wir das Modell mit den Trainingsdaten. Das Modell lernt dabei Zusammenhänge zwischen den Merkmalen in `X_train` und den Klassen in `y_train`.

**Aufgabe:**  
Trainieren Sie das Modell mit den Trainingsdaten.

**Lösung:**

In [24]:
# Modell trainieren
model.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=3, min_samples_leaf=10, random_state=42)

## Schritt 10: Vorhersagen auf Testdaten machen

**Erklärung:**  
Nach dem Training lassen wir das Modell Vorhersagen für die Testdaten machen. Die Ergebnisse speichern wir in `y_pred`. Diese Vorhersagen vergleichen wir später mit den echten Klassen aus `y_test`.

**Aufgabe:**  
Erstellen Sie Vorhersagen für die Testdaten und speichere sie in `y_pred`.

**Lösung:**

In [25]:
# Vorhersagen auf Testdaten machen
y_pred = model.predict(X_test)

In [39]:
# Wir erstellen eine neue Tabelle (DataFrame) zum Vergleichen
vergleich = pd.DataFrame({
    
    # Spalte mit den echten Klassen aus den Testdaten
    # .values wandelt die pandas Series in ein Array um
    "Echte Klasse": y_test.values,
    
    # Spalte mit den Vorhersagen des Modells
    "Vorhersage": y_pred
})

# Zeigt die ersten 5 Zeilen der Vergleichstabelle an
vergleich.head(30)

       Echte Klasse       Vorhersage
0   Iris-versicolor  Iris-versicolor
1       Iris-setosa      Iris-setosa
2    Iris-virginica   Iris-virginica
3   Iris-versicolor  Iris-versicolor
4   Iris-versicolor   Iris-virginica
5       Iris-setosa      Iris-setosa
6   Iris-versicolor  Iris-versicolor
7    Iris-virginica   Iris-virginica
8   Iris-versicolor  Iris-versicolor
9   Iris-versicolor  Iris-versicolor
10   Iris-virginica   Iris-virginica
11      Iris-setosa      Iris-setosa
12      Iris-setosa      Iris-setosa
13      Iris-setosa      Iris-setosa
14      Iris-setosa      Iris-setosa
15  Iris-versicolor  Iris-versicolor
16   Iris-virginica   Iris-virginica
17  Iris-versicolor  Iris-versicolor
18  Iris-versicolor  Iris-versicolor
19   Iris-virginica   Iris-virginica
20      Iris-setosa      Iris-setosa
21   Iris-virginica   Iris-virginica
22      Iris-setosa      Iris-setosa
23   Iris-virginica   Iris-virginica
24   Iris-virginica   Iris-virginica
25   Iris-virginica   Iris-virginica
26   Iris-virginica   Iris-virginica
27   Iris-virginica   Iris-virginica
28      Iris-setosa      Iris-setosa
29      Iris-setosa      Iris-setosa

## Schritt 11: Genauigkeit berechnen

**Erklärung:**  
Die Accuracy zeigt, wie viele Testbeispiele richtig klassifiziert wurden. Ein Wert von `1.0` bedeutet 100 Prozent richtig, ein Wert von `0.9` bedeutet 90 Prozent richtig.

**Aufgabe:**  
Berechnen Sie die Accuracy des Modells und geben Sie sie aus.

Verwenden Sie dafür die Funktion `accuracy_score` aus `sklearn.metrics`.
Vergleichen Sie die echten Werte (`y_test`) mit den Vorhersagen (`y_pred`).

**Lösung:**

In [46]:
# Genauigkeit berechnen
accuracy = accuracy_score(y_test, y_pred)
print(f"Genauigkeit: {accuracy:.2f} ({accuracy*100:.1f}%)")

Genauigkeit: 0.97 (96.7%)

## Schritt 12: Decision Tree visualisieren

**Erklärung:**  
Jetzt visualisieren wir den trainierten Entscheidungsbaum. Dadurch kann man sehen, welche Regeln der Baum gelernt hat und nach welchen Merkmalen er Entscheidungen trifft.

In [44]:
# Neue Blume vorhersagen
neue_blume = [[5.1, 3.5, 1.4, 0.2]]  # [SepalLength, SepalWidth, PetalLength, PetalWidth]
vorhersage = model.predict(neue_blume)
print(f"Vorhersage für die neue Blume: {vorhersage[0]}")

Vorhersage für die neue Blume: Iris-setosa

/home/bernard/miniconda3/envs/ml_env/lib/python3.9/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

## Schritt 13: Einzelne neue Blume vorhersagen

**Erklärung:**  
Zum Schluss testen wir das Modell mit einer neuen Blume. Die Werte müssen in der gleichen Reihenfolge angegeben werden wie die Spalten in `X`: `SepalLengthCm`, `SepalWidthCm`, `PetalLengthCm`, `PetalWidthCm`.

**Aufgabe:**  
Erstellen Sie eine neue Blume mit den Werten `[5.1, 3.5, 1.4, 0.2]` und lasse die Klasse vorhersagen.

**Lösung:**

In [47]:
# Neue Blume vorhersagen
neue_blume = [[5.1, 3.5, 1.4, 0.2]]  # [SepalLength, SepalWidth, PetalLength, PetalWidth]
vorhersage = model.predict(neue_blume)
print(f"Vorhersage für die neue Blume: {vorhersage[0]}")

Vorhersage für die neue Blume: Iris-setosa

/home/bernard/miniconda3/envs/ml_env/lib/python3.9/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(